DROP TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_DAY ON time_day;
CREATE TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_DAY
BEFORE INSERT OR UPDATE ON time_day
FOR EACH ROW
EXECUTE PROCEDURE UPDATE_TIMESTAMP_RANGE();

DROP TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_CAL_MTH ON time_cal_mth;
CREATE TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_CAL_MTH 
BEFORE INSERT OR UPDATE ON time_cal_mth
FOR EACH ROW
EXECUTE PROCEDURE UPDATE_TIMESTAMP_RANGE();

DROP TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_CAL_QTR ON time_cal_qtr;
CREATE TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_CAL_QTR 
BEFORE INSERT OR UPDATE ON time_cal_qtr
FOR EACH ROW
EXECUTE PROCEDURE UPDATE_TIMESTAMP_RANGE();

DROP TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_CAL_YEAR ON time_cal_year;
CREATE TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_CAL_YEAR 
BEFORE INSERT OR UPDATE ON time_cal_year
FOR EACH ROW
EXECUTE PROCEDURE UPDATE_TIMESTAMP_RANGE();

DROP TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_ISO_WEEK ON time_iso_week;
CREATE TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_ISO_WEEK 
BEFORE INSERT OR UPDATE ON time_iso_week
FOR EACH ROW
EXECUTE PROCEDURE UPDATE_TIMESTAMP_RANGE();

DROP TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_ISO_YEAR ON time_iso_year;
CREATE TRIGGER UPDATE_TIMESTAMP_RANGE_TIME_ISO_YEAR 
BEFORE INSERT OR UPDATE ON time_iso_year
FOR EACH ROW
EXECUTE PROCEDURE UPDATE_TIMESTAMP_RANGE();

DROP TRIGGER UPDATE_STARTEND_RANGES_BB_PRV_SCH ON bb_prv_sch;
CREATE TRIGGER UPDATE_STARTEND_RANGES_BB_PRV_SCH 
BEFORE INSERT OR UPDATE ON bb_prv_sch
FOR EACH ROW
EXECUTE PROCEDURE UPDATE_STARTEND_RANGES();
