#!/bin/bash

psql -h localhost -U root -d metrics -p 7432 -f all_booking_times.sql
psql -h localhost -U root -d metrics -p 7432 -f bb_ext_wrk_hrs.sql
psql -h localhost -U root -d metrics -p 7432 -f bb_prv_bus_hrs.sql
psql -h localhost -U root -d metrics -p 7432 -f bb_prv_sch.sql
psql -h localhost -U root -d metrics -p 7432 -f bb_wk_rtn.sql
psql -h localhost -U root -d metrics -p 7432 -f booking_pct_inc.sql
psql -h localhost -U root -d metrics -p 7432 -f build_jobs.sql
psql -h localhost -U root -d metrics -p 7432 -f ca_est_trd.sql
psql -h localhost -U root -d metrics -p 7432 -f ca_sku.sql
psql -h localhost -U root -d metrics -p 7432 -f ca_sku_trd.sql
psql -h localhost -U root -d metrics -p 7432 -f ca_trd.sql
psql -h localhost -U root -d metrics -p 7432 -f ci_cst.sql
psql -h localhost -U root -d metrics -p 7432 -f ci_cst_adr.sql
psql -h localhost -U root -d metrics -p 7432 -f dsk_adr.sql
psql -h localhost -U root -d metrics -p 7432 -f dsk_cst.sql
psql -h localhost -U root -d metrics -p 7432 -f dsk_cst_adr.sql
psql -h localhost -U root -d metrics -p 7432 -f dsk_cst_eml.sql
psql -h localhost -U root -d metrics -p 7432 -f dsk_cst_phn.sql
psql -h localhost -U root -d metrics -p 7432 -f dsk_eml.sql
psql -h localhost -U root -d metrics -p 7432 -f dsk_phn.sql
psql -h localhost -U root -d metrics -p 7432 -f dw_abr.sql
psql -h localhost -U root -d metrics -p 7432 -f dw_src.sql
psql -h localhost -U root -d metrics -p 7432 -f fb_inv.sql
psql -h localhost -U root -d metrics -p 7432 -f fb_inv_lin.sql
psql -h localhost -U root -d metrics -p 7432 -f fb_pmt.sql
psql -h localhost -U root -d metrics -p 7432 -f ga_pdc_stt.sql
psql -h localhost -U root -d metrics -p 7432 -f id_com_itf.sql
psql -h localhost -U root -d metrics -p 7432 -f id_usr.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_bll.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_bll_hst.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_bll_pho.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_cms_rat.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_cst.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_cst_acc.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_cst_pmt.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_cst_pmt_hst.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_cst_pmt_mth.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_inv_lin_itm.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_inv_scp_adj.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_manual.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_ord_pmt_prf.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_ord_prc_fee.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_pdc_crd.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_pmt_prc.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_prv_acc.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_prv_pmt.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_ptl_ord_inv_amt.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_sch_pmt_cfg.sql
psql -h localhost -U root -d metrics -p 7432 -f inv_wip.sql
psql -h localhost -U root -d metrics -p 7432 -f iso_18_weeks_back.sql
psql -h localhost -U root -d metrics -p 7432 -f jm_cst_job_mgr.sql
psql -h localhost -U root -d metrics -p 7432 -f jm_grp_cs_cty.sql
psql -h localhost -U root -d metrics -p 7432 -f jm_job_mgr_avl.sql
psql -h localhost -U root -d metrics -p 7432 -f jm_job_mgr_avl_hst.sql
psql -h localhost -U root -d metrics -p 7432 -f jobs_manual.sql
psql -h localhost -U root -d metrics -p 7432 -f jobs_manual_cst.sql
psql -h localhost -U root -d metrics -p 7432 -f jobs_manual_extra.sql
psql -h localhost -U root -d metrics -p 7432 -f jobs_manual_prv.sql
psql -h localhost -U root -d metrics -p 7432 -f lb_att_agg.sql
psql -h localhost -U root -d metrics -p 7432 -f lb_att_chn.sql
psql -h localhost -U root -d metrics -p 7432 -f lb_att_cli_typ.sql
psql -h localhost -U root -d metrics -p 7432 -f lb_att_evt.sql
psql -h localhost -U root -d metrics -p 7432 -f lb_att_htp_req.sql
psql -h localhost -U root -d metrics -p 7432 -f lb_att_rec.sql
psql -h localhost -U root -d metrics -p 7432 -f maj_evt.sql
psql -h localhost -U root -d metrics -p 7432 -f manual_pros.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_cbsa.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_cbsa_csa.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_cbsa_cty.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_cbsa_pop.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_cbsa_type.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_csa.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_csa_cty.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_cty_pos.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_fips_county.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_fips_place.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_fips_state.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_met_div.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_met_div_cty.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_zcta_cbsa.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_zcta_county.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_zcta_place.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_zip.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_zip_city.sql
psql -h localhost -U root -d metrics -p 7432 -f mi_zip_county.sql
psql -h localhost -U root -d metrics -p 7432 -f mk_mkt_spd.sql
psql -h localhost -U root -d metrics -p 7432 -f mpo_nhd_geo.sql
psql -h localhost -U root -d metrics -p 7432 -f mpo_nhd_nam.sql
psql -h localhost -U root -d metrics -p 7432 -f mpo_nhd_zip.sql
psql -h localhost -U root -d metrics -p 7432 -f mpo_zip.sql
psql -h localhost -U root -d metrics -p 7432 -f mpo_zip_bnd.sql
psql -h localhost -U root -d metrics -p 7432 -f mpo_zip_cnt.sql
psql -h localhost -U root -d metrics -p 7432 -f ms_mag_lst.sql
psql -h localhost -U root -d metrics -p 7432 -f ms_mag_lst_itm.sql
psql -h localhost -U root -d metrics -p 7432 -f ms_mag_lst_itm_gesv.sql
psql -h localhost -U root -d metrics -p 7432 -f msg_cnv.sql
psql -h localhost -U root -d metrics -p 7432 -f msg_cnv_ptp.sql
psql -h localhost -U root -d metrics -p 7432 -f msg_com.sql
psql -h localhost -U root -d metrics -p 7432 -f msg_com_inb.sql
psql -h localhost -U root -d metrics -p 7432 -f msg_com_med.sql
psql -h localhost -U root -d metrics -p 7432 -f msg_com_otb.sql
psql -h localhost -U root -d metrics -p 7432 -f msg_com_rcp.sql
psql -h localhost -U root -d metrics -p 7432 -f msg_gtw_nbr.sql
psql -h localhost -U root -d metrics -p 7432 -f msg_gtw_rte.sql
psql -h localhost -U root -d metrics -p 7432 -f ord_ann_sts.sql
psql -h localhost -U root -d metrics -p 7432 -f ord_day_sts.sql
psql -h localhost -U root -d metrics -p 7432 -f ord_eow_sts.sql
psql -h localhost -U root -d metrics -p 7432 -f ord_inv_amt.sql
psql -h localhost -U root -d metrics -p 7432 -f ord_itm_gesv.sql
psql -h localhost -U root -d metrics -p 7432 -f ord_mth_sts.sql
psql -h localhost -U root -d metrics -p 7432 -f ord_qtr_sts.sql
psql -h localhost -U root -d metrics -p 7432 -f ord_tgt_mth.sql
psql -h localhost -U root -d metrics -p 7432 -f os_act_avl.sql
psql -h localhost -U root -d metrics -p 7432 -f os_act_avl_rsp.sql
psql -h localhost -U root -d metrics -p 7432 -f os_cst_ord.sql
psql -h localhost -U root -d metrics -p 7432 -f os_cst_ord_hst.sql
psql -h localhost -U root -d metrics -p 7432 -f os_cst_ord_hst_chg.sql
psql -h localhost -U root -d metrics -p 7432 -f os_cst_ord_itm.sql
psql -h localhost -U root -d metrics -p 7432 -f os_cst_ord_trn.sql
psql -h localhost -U root -d metrics -p 7432 -f os_cst_ref.sql
psql -h localhost -U root -d metrics -p 7432 -f os_cst_ref_itm_gesv.sql
psql -h localhost -U root -d metrics -p 7432 -f os_prd_rsn.sql
psql -h localhost -U root -d metrics -p 7432 -f os_ptl_ord.sql
psql -h localhost -U root -d metrics -p 7432 -f os_ptl_ord_hst.sql
psql -h localhost -U root -d metrics -p 7432 -f os_ptl_ord_itm_gesv.sql
psql -h localhost -U root -d metrics -p 7432 -f os_ptl_ord_prv_asn.sql
psql -h localhost -U root -d metrics -p 7432 -f os_srv_trk.sql
psql -h localhost -U root -d metrics -p 7432 -f sales_calls.sql
psql -h localhost -U root -d metrics -p 7432 -f series_back.sql
psql -h localhost -U root -d metrics -p 7432 -f service_providers.sql
psql -h localhost -U root -d metrics -p 7432 -f sf_prv_obd.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_expt.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_prv_trd.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv_ptp.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv_ptp_rsp.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv_qst.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv_qst_opt.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv_qst_sec.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv_rsp_alr.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv_srv_qst.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv_stt.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_srv_svn.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_svc_prv_con.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_svc_prv_crw.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_svc_prv_cst.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_svc_prv_cvg.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_svc_prv_expt.sql
psql -h localhost -U root -d metrics -p 7432 -f shp_svc_prv_map.sql
psql -h localhost -U root -d metrics -p 7432 -f ss_mag_lst_met.sql
psql -h localhost -U root -d metrics -p 7432 -f ss_mtc_tag_met.sql
psql -h localhost -U root -d metrics -p 7432 -f ss_reg_met.sql
psql -h localhost -U root -d metrics -p 7432 -f ss_sku_sum_met.sql
psql -h localhost -U root -d metrics -p 7432 -f sync_test.sql
psql -h localhost -U root -d metrics -p 7432 -f test_data.sql
psql -h localhost -U root -d metrics -p 7432 -f time_cal_mth.sql
psql -h localhost -U root -d metrics -p 7432 -f time_cal_qtr.sql
psql -h localhost -U root -d metrics -p 7432 -f time_cal_year.sql
psql -h localhost -U root -d metrics -p 7432 -f time_day.sql
psql -h localhost -U root -d metrics -p 7432 -f time_iso_week.sql
psql -h localhost -U root -d metrics -p 7432 -f time_iso_year.sql
psql -h localhost -U root -d metrics -p 7432 -f wa_sos_ubi.sql
psql -h localhost -U root -d metrics -p 7432 -f wf_tds.sql
psql -h localhost -U root -d metrics -p 7432 -f wf_wrk_itm.sql
psql -h localhost -U root -d metrics -p 7432 -f wf_wrk_itm_act.sql
psql -h localhost -U root -d metrics -p 7432 -f wf_wrk_itm_act_trn.sql
psql -h localhost -U root -d metrics -p 7432 -f wf_wrk_itm_sta.sql
psql -h localhost -U root -d metrics -p 7432 -f wf_wrk_itm_sts_sla.sql
psql -h localhost -U root -d metrics -p 7432 -f wf_wrk_itm_tds.sql
psql -h localhost -U root -d metrics -p 7432 -f wf_wrk_itm_typ_wrk_itm_sts.sql
