CREATE OR REPLACE FUNCTION NOT_EQUALS_TEXT_INTEGER (textarg TEXT, intarg INTEGER)
RETURNS BOOLEAN AS $$
BEGIN
	IF (textarg::INTEGER=intarg) THEN
		RETURN FALSE;
	ELSE
		RETURN TRUE;
	END IF;
END; 
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION NOT_EQUALS_TEXT_INTEGER (intarg INTEGER, textarg TEXT)
RETURNS BOOLEAN AS $$
BEGIN
	IF (textarg::INTEGER=intarg) THEN
		RETURN FALSE;
	ELSE
		RETURN TRUE;
	END IF;
END; 
$$ LANGUAGE plpgsql;
